services:
  lexcodex:
    image: ghcr.io/jpvargasdev/lexcodex:0.0.5
    # container_name: lexcodex   # ← remove to avoid collisions
    env_file:
      - ../../configs/lexcodex.env
      - ../../secrets/.runtime/lexcodex.env

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s

    restart: unless-stopped
