services:
  pg-main:
    image: docker.io/library/postgres:17
    container_name: pg-main
    env_file:
      - ../../configs/postgres.env
      - ../../secrets/.runtime/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  lexcodex:
    image: ghcr.io/jpvargasdev/lexcodex:0.0.5 # {"magos": {"policy": "semver", "repo": "ghcr.io/jpvargasdev/lexcodex"}}
    container_name: lexcodex
    env_file:
      - ../../configs/lexcodex.env
      - ../../secrets/.runtime/lexcodex.env
    depends_on:
      pg-main:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: on-failure:5

volumes:
  pgdata: {}
