services:
  machinespirittimetable:
    image: ghcr.io/jpvargasdev/machinespirittimetable:0.0.8 # {"magos": {"policy": "semver", "repo": "ghcr.io/jpvargasdev/machinespirittimetable"}}
    container_name: machinespirittimetable
    privileged: true

    networks:
      - singularity

    ports:
      - "8080:8080"

    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/var/run/dbus/system_bus_socket"
    env_file:
      - ../../configs/machinespirittimetable.env

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 2m
      timeout: 3s
      retries: 2
      start_period: 30s

    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    command: ["run", "-f", "medium", "-c", "yellow"]

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=singularity"
      - "traefik.http.services.machinespirittimetable.loadbalancer.server.port=8080"
      # - "traefik.http.routers.machinespirittimetable.rule=Host(`machinespirittimetable.tu-dominio.se`)"
      # - "traefik.http.routers.machinespirittimetable.entrypoints=websecure"
      # - "traefik.http.routers.machinespirittimetable.tls=true"

networks:
  singularity:
    external: true
