version: "3.9"

services:
  pg-main:
    image: postgres:18
    container_name: pg-main
    env_file:
      - ../../configs/postgres.env          
      - ../../secrets/postgres.secret.env   
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }

networks:
  backend:
    external: true
